### ISSUE TITLE
Parser - Switch Statements

### ISSUE THREAD

**Issue by CalebLItalien** [UnionCompilerDesign/compiler_core#100]
### Details
Add support for `switch`, `case`, and `default` to the parser through a single unified function `parse_switch_statement`. 

### Issue Type
- [X] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Refactoring
- [ ] Other:

### Requirements
- Implementation of switch statements and unit testing

### Notes

**Comment by CalebLItalien** [comment]
@tbreimer14 are you using the match statement code for this? I think the match statement code should be pretty similar.

**Comment by tbreimer14** [comment]
Exactly what I've been doing! Just think we need a parse_case_block method too to handle "break;" indicating the end of a case block.

**Comment by CalebLItalien** [comment]
We already have a 'parse_break' I believe? Do we want it to be a parser error if there isn't a break statement in a case?

**Comment by tbreimer14** [comment]
Right, I forgot we don't actually need a break token to end a switch block. I don't see a parse_break on the frontend branch, is that supposed to parse the token? I think we would still need a special method to parse a case body though, since it would end when the next case started, and not with a "}" like parse_block expects. Definitely could be wrong though, let me know if I'm misunderstanding something.
